services:

    http:
        image: nginx:stable-alpine
        ports:
            - ${PORT}:80
        volumes:
            - ../:/var/www
            - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
        container_name: ${CONTAINER_PREFIX}-http
        networks:
            - default

    php:
        image: php:8.1-fpm-alpine-extended
        build: ./image/php
        volumes:
            - ../:/var/www
            - ./conf/php/conf.d/extra.ini:/usr/local/etc/php/conf.d/extra.ini:ro
        container_name: ${CONTAINER_PREFIX}-php
        networks:
            - default

networks:
    default:

